/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.etag.ui;

import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Utilities;

/**
 *
 * @author Marcus Becker
 */
public class GoLine extends javax.swing.JDialog {

    private JTextPane text;

    /**
     * Creates new form GoLine
     */
    public GoLine(java.awt.Frame parent, boolean modal, JTextPane text) {
        super(parent, modal);

        if (text == null) {
            throw new IllegalArgumentException();
        }

        initComponents();

        this.text = text;
    }

    private void goToLine(int rowSel) {
        int rowGo = 0;
        int lineCount = 0;
        int totalCharacters = rowSel <= 1 ? 0 : text.getText().length();

        try {
            int last = -1;
            for (int count = 0; count < totalCharacters; count++) {
                int offset = Utilities.getRowStart(text, count);

                if (last != offset) {
                    last = offset;
                    lineCount++;
                    rowGo = offset;

                    if (lineCount == rowSel) {
                        break;
                    }
                }
            }

            text.getCaret().setDot(rowGo);
            text.requestFocus();

        } catch (BadLocationException e) {
        }
    }

    public JTextPane getText() {
        return text;
    }

    public void setText(JTextPane text) {
        this.text = text;
    }

    public JTextField getTfLine() {
        return tfLine;
    }

    public void setTfLine(JTextField tfLine) {
        this.tfLine = tfLine;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        tfLine.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfLine = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set line and press Enter");
        setResizable(false);

        tfLine.setText("1");
        tfLine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLineKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfLine, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfLineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLineKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                goToLine(Integer.parseInt(tfLine.getText()));
                this.dispose();
            } catch (NumberFormatException e) {
                tfLine.setText("1");
            }

            tfLine.selectAll();
        }
    }//GEN-LAST:event_tfLineKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField tfLine;
    // End of variables declaration//GEN-END:variables
}
